import { Router } from "express";
import PDFDocument from "pdfkit";

const router = Router();

router.post("/", async (req, res) => {
  try {
    const analysisData = req.body;

    if (!analysisData) {
      return res.status(400).json({ error: "Analysis data is required" });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="webperf-report-${Date.now()}.pdf"`
    );

    doc.pipe(res);

    // Title
    doc.fontSize(24).text("AI WebPerf Doctor Report", { align: "center" });
    doc.moveDown();

    // URL and Score
    doc.fontSize(16).text(`URL: ${analysisData.lighthouse.url}`);
    doc
      .fontSize(18)
      .fillColor("blue")
      .text(`Performance Score: ${analysisData.lighthouse.score}/100`, {
        align: "center",
      });
    doc.fillColor("black");
    doc.moveDown();

    // Metrics Section
    doc.fontSize(16).text("Core Web Vitals", { underline: true });
    doc.moveDown(0.5);
    const metrics = analysisData.lighthouse.metrics;
    doc.fontSize(12);
    doc.text(
      `LCP (Largest Contentful Paint): ${metrics.lcp?.toFixed(0) || "N/A"}ms`
    );
    doc.text(`FID (First Input Delay): ${metrics.fid?.toFixed(0) || "N/A"}ms`);
    doc.text(
      `CLS (Cumulative Layout Shift): ${metrics.cls?.toFixed(3) || "N/A"}`
    );
    doc.text(
      `FCP (First Contentful Paint): ${metrics.fcp?.toFixed(0) || "N/A"}ms`
    );
    doc.text(
      `TBT (Total Blocking Time): ${metrics.tbt?.toFixed(0) || "N/A"}ms`
    );
    doc.moveDown();

    // AI Analysis Summary
    doc.fontSize(16).text("AI Analysis Summary", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text(analysisData.aiAnalysis.summary);
    doc.moveDown();

    // Issues
    doc.fontSize(16).text("Performance Issues", { underline: true });
    doc.moveDown(0.5);
    analysisData.aiAnalysis.issues.forEach((issue, index) => {
      doc
        .fontSize(12)
        .text(`${index + 1}. ${issue.title} [${issue.severity.toUpperCase()}]`);
      doc.fontSize(10).fillColor("gray").text(issue.description);
      doc.text(`Impact: ${issue.impact}`);
      doc.fillColor("black");
      doc.moveDown(0.5);
    });

    // Recommendations
    doc.fontSize(16).text("Recommendations", { underline: true });
    doc.moveDown(0.5);
    analysisData.aiAnalysis.recommendations.forEach((rec, index) => {
      doc
        .fontSize(12)
        .text(
          `${index + 1}. ${rec.title} [${rec.priority.toUpperCase()} Priority]`
        );
      doc.fontSize(10).fillColor("gray").text(rec.description);
      doc.text(`Expected Improvement: ${rec.expectedImprovement}`);
      doc.fillColor("black");
      doc.moveDown(0.5);
    });

    // Code Examples
    if (analysisData.aiAnalysis.codeExamples.length > 0) {
      doc.addPage();
      doc.fontSize(16).text("Code Examples", { underline: true });
      doc.moveDown(0.5);
      analysisData.aiAnalysis.codeExamples.forEach((example, index) => {
        doc.fontSize(12).text(`${index + 1}. ${example.title}`);
        doc.fontSize(10).fillColor("blue").text(example.description);
        doc.fillColor("black");
        doc.moveDown(0.3);
        doc.font("Courier").fontSize(9).text(example.code, {
          align: "left",
          indent: 10,
        });
        doc.font("Helvetica");
        doc.moveDown();
      });
    }

    // Footer
    doc
      .fontSize(8)
      .fillColor("gray")
      .text(
        `Generated by AI WebPerf Doctor on ${new Date().toLocaleString()}`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    console.error("Export error:", error);
    res.status(500).json({
      error: "Failed to generate PDF",
      message: error.message,
    });
  }
});

export { router as exportRoute };
